tag_prefix = "v"
branch_whitelist = [
  "main"
]

pre_bump_hooks = [
  "mvn versions:set -DnewVersion='{{version}}' -DgenerateBackupPoms=false --batch-mode --errors",
  "mvn clean package -DskipTests --batch-mode --activate-profiles ci --errors --strict-checksums --update-snapshots --fail-fast"
]
post_bump_hooks = [
  "mvn versions:set -DnewVersion='0.0.1-DEV-SNAPSHOT' -DgenerateBackupPoms=false --batch-mode --errors",
  "git commit --all --message='chore: prepare for next development iteration [ci skip]'",
  "git push",
  "git push origin {{version}}"
]

[commit_types]
fix = { changelog_title = "ğŸ› Bug Fixes" }
feat = { changelog_title = "ğŸŒŸ Features" }
build = { changelog_title = "ğŸ—ï¸ Build System" }
ci = { changelog_title = "ğŸ“¦ Continuous Integration" }
docs = { changelog_title = "ğŸ“– Documentation" }
chore = { changelog_title = "ğŸ§¹ Miscellaneous Chores" }
refactor = { changelog_title = "ğŸ› ï¸ Refactoring" }
revert = { changelog_title = "â†©ï¸ Revert" }
style = { changelog_title = "ğŸ–Œï¸ Style" }
test = { changelog_title = "âœ… Tests" }
perf = { changelog_title = "âš¡ Performances" }

[changelog]
path = ".github/CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "Djaytan"
repository = "mc-jobs-reborn-patch-place-break"
authors = [
  { signature = "Djaytan", username = "Djaytan" }
]
