tag_prefix = "v"

pre_bump_hooks = [
  "git switch --create release/{{version_tag}}",
]
post_bump_hooks = [
  "git commit --amend --message 'docs(changelog): release {{version_tag}}'",
  "git push --set-upstream origin release/{{version_tag}}"
]

[commit_types]
feat = { changelog_title = "ğŸŒŸ Features" }
fix = { changelog_title = "ğŸ› Bug Fixes" }
perf = { changelog_title = "âš¡ Performances" }
revert = { changelog_title = "â†©ï¸ Revert" }
refactor = { changelog_title = "ğŸ› ï¸ Refactoring" }
docs = { changelog_title = "ğŸ“– Documentation" }
test = { changelog_title = "âœ… Tests" }
build = { changelog_title = "ğŸ—ï¸ Build System" }
ci = { changelog_title = "ğŸ“¦ Continuous Integration" }
chore = { changelog_title = "ğŸ§¹ Miscellaneous Chores" }
style = { changelog_title = "ğŸ–Œï¸ Style" }

[changelog]
path = ".github/CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "Djaytan"
repository = "mc-jobs-reborn-patch-place-break"
authors = [
  { signature = "Djaytan", username = "Djaytan" }
]
